# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements-prod.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .
  system_packages: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: [epub]

