version: 2.1

# Pipeline template
shared: &shared
    docker:
        - image: continuumio/miniconda3
          environment:
             BASH_ENV: ~/.bashrc
    working_directory: ~/monitor-server--api.ci
    steps:
        - checkout
        - run:
            name: "Setup Environment"
            command: |
                conda create -n ci ${CI_PYTHON} -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda install -n ci --file requirements-dev.txt -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                conda init bash
        - run:
            name: "Prepare Project"
            command: |
                conda activate ci
                cp requirements-dev.txt requirements.txt
                python setup.py develop
        - run:
            name: "Testing"
            command: |
                conda init bash
                conda activate ci
                mkdir test-results
                pytest -vv --junit-xml=test-results/junit.xml
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results

# Workflow definition
workflows:
    standard:
        jobs:
            - monitor-py37:
                filters:
                    tags:
                        only: /.*/
            - monitor-py38:
                filters:
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - monitor-py37
                    - monitor-py38
                filters:
                    tags:
                        only: /^[a-zA-Z].*/
                    branches:
                        ignore: /.*/
    nightly:
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - nightly_build

# Jobs definition
jobs:
    monitor-py37:
        environment:
            CI_PYTHON: 'python=3.7'
        <<: *shared
    monitor-py38:
        environment:
            CI_PYTHON: 'python=3.8'
        <<: *shared
    nightly_build:
        environment:
            CI_PYTHON: 'python'
        <<: *shared
    deploy:
        docker:
            - image: continuumio/miniconda3
              environment:
                BASH_ENV: ~/.bashrc
        working_directory: ~/pytest-monitor.ci
        steps:
            - checkout
            - run:
                name: "Prepare for deployment"
                command: |
                    conda create -n ci python=3.8 twine wheel setuptools -c https://conda.anaconda.org/conda-forge -c defaults -c anaconda -y
                    conda init bash
                    echo -e "[pypi]" >> ~/.pypirc
                    echo -e "username = __token__" >> ~/.pypirc
                    echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

            - run:
                name: "Package Project"
                command: |
                    conda activate ci
                    python setup.py sdist bdist_wheel
            - run:
                name: "Publish"
                command: |
                    conda init bash
                    conda activate ci
                    twine upload dist/*
